<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Municipio;
use Illuminate\Support\Facades\DB;

class SeederMunicipio extends Seeder {
	
	public function run() 
	{
        /**
         * Run the database seeds.
         *
         * @return void
         */
        //eliminar datos
        Municipio::truncate();
        DB::statement('ALTER SEQUENCE municipio_id_seq RESTART WITH 1');
		$municipios = [
			['id_departamento'=>'1','nombre'=>'Atiquizaya'],
			['id_departamento'=>'1','nombre'=>'El Refugio'],
			['id_departamento'=>'1','nombre'=>'San Lorenzo'],
			['id_departamento'=>'1','nombre'=>'Turín'],
			['id_departamento'=>'1','nombre'=>'Ahuachapán'],
			['id_departamento'=>'1','nombre'=>'Apaneca'],
			['id_departamento'=>'1','nombre'=>'Concepción de Ataco'],
			['id_departamento'=>'1','nombre'=>'Tacuba'],
			['id_departamento'=>'1','nombre'=>'Guaymango'],
			['id_departamento'=>'1','nombre'=>'Jujutla'],
			['id_departamento'=>'1','nombre'=>'San Francisco Menéndez'],
			['id_departamento'=>'1','nombre'=>'San Pedro Puxtla'],
			['id_departamento'=>'2','nombre'=>'Dolores'],
			['id_departamento'=>'2','nombre'=>'Guacotecti'],
			['id_departamento'=>'2','nombre'=>'Sensuntepeque'],
			['id_departamento'=>'2','nombre'=>'San Isidro'],
			['id_departamento'=>'2','nombre'=>'Victoria'],
			['id_departamento'=>'2','nombre'=>'Cinquera'],
			['id_departamento'=>'2','nombre'=>'Ilobasco'],
			['id_departamento'=>'2','nombre'=>'Jutiapa'],
			['id_departamento'=>'2','nombre'=>'Tejutepeque'],
			['id_departamento'=>'3','nombre'=>'La Palma'],
			['id_departamento'=>'3','nombre'=>'Citalá'],
			['id_departamento'=>'3','nombre'=>'San Ignacio'],
			['id_departamento'=>'3','nombre'=>'Agua Caliente'],
			['id_departamento'=>'3','nombre'=>'Dulce Nombre de María'],
			['id_departamento'=>'3','nombre'=>'El Paraíso'],
			['id_departamento'=>'3','nombre'=>'La Reina'],
			['id_departamento'=>'3','nombre'=>'Nueva Concepción'],
			['id_departamento'=>'3','nombre'=>'San Fernando'],
			['id_departamento'=>'3','nombre'=>'San Francisco Morazán'],
			['id_departamento'=>'3','nombre'=>'San Rafael'],
			['id_departamento'=>'3','nombre'=>'Santa Rita'],
			['id_departamento'=>'3','nombre'=>'Tejutla'],
			['id_departamento'=>'3','nombre'=>'Arcatao'],
			['id_departamento'=>'3','nombre'=>'Azacualpa'],
			['id_departamento'=>'3','nombre'=>'Chalatenango'],
			['id_departamento'=>'3','nombre'=>'Comalapa'],
			['id_departamento'=>'3','nombre'=>'Concepción Quezaltepeque'],
			['id_departamento'=>'3','nombre'=>'El Carrizal'],
			['id_departamento'=>'3','nombre'=>'La Laguna'],
			['id_departamento'=>'3','nombre'=>'Las Vueltas'],
			['id_departamento'=>'3','nombre'=>'Nombre de Jesús'],
			['id_departamento'=>'3','nombre'=>'Nueva Trinidad'],
			['id_departamento'=>'3','nombre'=>'Ojos de Agua'],
			['id_departamento'=>'3','nombre'=>'Potonico'],
			['id_departamento'=>'3','nombre'=>'San Antonio de la Cruz (San Antonio La Cruz)'],
			['id_departamento'=>'3','nombre'=>'San Antonio Los Ranchos (San Antonio Ranchos)'],
			['id_departamento'=>'3','nombre'=>'San Francisco Lempa'],
			['id_departamento'=>'3','nombre'=>'San Isidro Labrador'],
			['id_departamento'=>'3','nombre'=>'San José Cancasque'],
			['id_departamento'=>'3','nombre'=>'San José Las Flores'],
			['id_departamento'=>'3','nombre'=>'San Luis del Carmen'],
			['id_departamento'=>'3','nombre'=>'San Miguel de Mercedes'],
			['id_departamento'=>'4','nombre'=>'Oratorio de Concepción'],
			['id_departamento'=>'4','nombre'=>'San Bartolomé Perulapía'],
			['id_departamento'=>'4','nombre'=>'San José Guayabal'],
			['id_departamento'=>'4','nombre'=>'San Pedro Perulapán'],
			['id_departamento'=>'4','nombre'=>'Suchitoto'],
			['id_departamento'=>'4','nombre'=>'Candelaria'],
			['id_departamento'=>'4','nombre'=>'Cojutepeque'],
			['id_departamento'=>'4','nombre'=>'El Carmen'],
			['id_departamento'=>'4','nombre'=>'El Rosario'],
			['id_departamento'=>'4','nombre'=>'Monte San Juan'],
			['id_departamento'=>'4','nombre'=>'San Cristóbal'],
			['id_departamento'=>'4','nombre'=>'San Rafael Cedros'],
			['id_departamento'=>'4','nombre'=>'San Ramón'],
			['id_departamento'=>'4','nombre'=>'Santa Cruz Analquito'],
			['id_departamento'=>'4','nombre'=>'Santa Cruz Michapa'],
			['id_departamento'=>'4','nombre'=>'Tenancingo'],
			['id_departamento'=>'5','nombre'=>'Quezaltepeque'],
			['id_departamento'=>'5','nombre'=>'San Matías'],
			['id_departamento'=>'5','nombre'=>'San Pablo Tacachico'],
			['id_departamento'=>'5','nombre'=>'Ciudad Arce'],
			['id_departamento'=>'5','nombre'=>'San Juan Opico'],
			['id_departamento'=>'5','nombre'=>'Colón'],
			['id_departamento'=>'5','nombre'=>'Jayaque'],
			['id_departamento'=>'5','nombre'=>'Sacacoyo'],
			['id_departamento'=>'5','nombre'=>'Talnique'],
			['id_departamento'=>'5','nombre'=>'Tepecoyo'],
			['id_departamento'=>'5','nombre'=>'Antiguo Cuscatlán'],
			['id_departamento'=>'5','nombre'=>'Huizúcar'],
			['id_departamento'=>'5','nombre'=>'Nuevo Cuscatlán'],
			['id_departamento'=>'5','nombre'=>'San José Villanueva'],
			['id_departamento'=>'5','nombre'=>'Zaragoza'],
			['id_departamento'=>'5','nombre'=>'Coastal La Libertad'],
			['id_departamento'=>'5','nombre'=>'Chiltiupán'],
			['id_departamento'=>'5','nombre'=>'Jicalapa'],
			['id_departamento'=>'5','nombre'=>'La Libertad'],
			['id_departamento'=>'5','nombre'=>'Tamanique'],
			['id_departamento'=>'5','nombre'=>'Teotepeque'],
			['id_departamento'=>'5','nombre'=>'Comasagua'],
			['id_departamento'=>'5','nombre'=>'Santa Tecla'],
			['id_departamento'=>'6','nombre'=>'Cuyultitán'],
			['id_departamento'=>'6','nombre'=>'Olocuilta'],
			['id_departamento'=>'6','nombre'=>'San Francisco Chinameca'],
			['id_departamento'=>'6','nombre'=>'San Juan Talpa'],
			['id_departamento'=>'6','nombre'=>'San Luis Talpa'],
			['id_departamento'=>'6','nombre'=>'San Pedro Masahuat'],
			['id_departamento'=>'6','nombre'=>'Tapalhuaca'],
			['id_departamento'=>'6','nombre'=>'El Rosario'],
			['id_departamento'=>'6','nombre'=>'Jerusalén'],
			['id_departamento'=>'6','nombre'=>'Mercedes La Ceiba'],
			['id_departamento'=>'6','nombre'=>'Paraíso de Osorio'],
			['id_departamento'=>'6','nombre'=>'San Antonio Masahuat'],
			['id_departamento'=>'6','nombre'=>'San Emigdio'],
			['id_departamento'=>'6','nombre'=>'San Juan Tepezontes'],
			['id_departamento'=>'6','nombre'=>'San Luis La Herradura'],
			['id_departamento'=>'6','nombre'=>'San Miguel Tepezontes'],
			['id_departamento'=>'6','nombre'=>'San Pedro Nonualco'],
			['id_departamento'=>'6','nombre'=>'Santa María Ostuma'],
			['id_departamento'=>'6','nombre'=>'Santiago Nonualco'],
			['id_departamento'=>'6','nombre'=>'San Juan Nonualco'],
			['id_departamento'=>'6','nombre'=>'San Rafael Obrajuelo'],
			['id_departamento'=>'6','nombre'=>'Zacatecoluca'],
			['id_departamento'=>'7','nombre'=>'Anamorós'],
			['id_departamento'=>'7','nombre'=>'Bolívar'],
			['id_departamento'=>'7','nombre'=>'Concepción de Oriente'],
			['id_departamento'=>'7','nombre'=>'El Sauce'],
			['id_departamento'=>'7','nombre'=>'Lislique'],
			['id_departamento'=>'7','nombre'=>'Nueva Esparta'],
			['id_departamento'=>'7','nombre'=>'Pasaquina'],
			['id_departamento'=>'7','nombre'=>'Polorós'],
			['id_departamento'=>'7','nombre'=>'San José'],
			['id_departamento'=>'7','nombre'=>'Santa Rosa de Lima'],
			['id_departamento'=>'7','nombre'=>'Conchagua'],
			['id_departamento'=>'7','nombre'=>'El Carmen'],
			['id_departamento'=>'7','nombre'=>'Intipucá'],
			['id_departamento'=>'7','nombre'=>'La Unión'],
			['id_departamento'=>'7','nombre'=>'Meanguera del Golfo'],
			['id_departamento'=>'7','nombre'=>'San Alejo'],
			['id_departamento'=>'7','nombre'=>'Yayantique'],
			['id_departamento'=>'7','nombre'=>'Yucuaiquín'],
			['id_departamento'=>'8','nombre'=>'Arambala'],
			['id_departamento'=>'8','nombre'=>'Cacaopera'],
			['id_departamento'=>'8','nombre'=>'Corinto'],
			['id_departamento'=>'8','nombre'=>'El Rosario'],
			['id_departamento'=>'8','nombre'=>'Joateca'],
			['id_departamento'=>'8','nombre'=>'Jocoaitique'],
			['id_departamento'=>'8','nombre'=>'Meanguera'],
			['id_departamento'=>'8','nombre'=>'Perquín'],
			['id_departamento'=>'8','nombre'=>'San Fernando'],
			['id_departamento'=>'8','nombre'=>'San Isidro'],
			['id_departamento'=>'8','nombre'=>'Torola'],
			['id_departamento'=>'8','nombre'=>'Chilanga'],
			['id_departamento'=>'8','nombre'=>'Delicias de Concepción'],
			['id_departamento'=>'8','nombre'=>'El Divisadero'],
			['id_departamento'=>'8','nombre'=>'Gualococti'],
			['id_departamento'=>'8','nombre'=>'Guatajiagua'],
			['id_departamento'=>'8','nombre'=>'Jocoro'],
			['id_departamento'=>'8','nombre'=>'Lolotiquillo'],
			['id_departamento'=>'8','nombre'=>'Osicala'],
			['id_departamento'=>'8','nombre'=>'San Carlos'],
			['id_departamento'=>'8','nombre'=>'San Francisco Gotera'],
			['id_departamento'=>'8','nombre'=>'San Simón'],
			['id_departamento'=>'8','nombre'=>'Sensembra'],
			['id_departamento'=>'8','nombre'=>'Sociedad'],
			['id_departamento'=>'8','nombre'=>'Yamabal'],
			['id_departamento'=>'8','nombre'=>'Yoloaiquín'],
			['id_departamento'=>'9','nombre'=>'Carolina'],
			['id_departamento'=>'9','nombre'=>'Chapeltique'],
			['id_departamento'=>'9','nombre'=>'Ciudad Barrios'],
			['id_departamento'=>'9','nombre'=>'Nuevo Edén de San Juan'],
			['id_departamento'=>'9','nombre'=>'San Antonio'],
			['id_departamento'=>'9','nombre'=>'San Gerardo'],
			['id_departamento'=>'9','nombre'=>'San Luis de la Reina'],
			['id_departamento'=>'9','nombre'=>'Sesori'],
			['id_departamento'=>'9','nombre'=>'Chirilagua'],
			['id_departamento'=>'9','nombre'=>'Comacarán'],
			['id_departamento'=>'9','nombre'=>'Moncagua'],
			['id_departamento'=>'9','nombre'=>'Quelepa'],
			['id_departamento'=>'9','nombre'=>'Uluazapa'],
			['id_departamento'=>'9','nombre'=>'San Miguel'],
			['id_departamento'=>'9','nombre'=>'Chinameca'],
			['id_departamento'=>'9','nombre'=>'El Tránsito'],
			['id_departamento'=>'9','nombre'=>'Lolotique'],
			['id_departamento'=>'9','nombre'=>'Nueva Guadalupe'],
			['id_departamento'=>'9','nombre'=>'San Jorge'],
			['id_departamento'=>'9','nombre'=>'San Rafael (San Rafael Oriente)'],
			['id_departamento'=>'10','nombre'=>'Aguilares'],
			['id_departamento'=>'10','nombre'=>'El Paisnal'],
			['id_departamento'=>'10','nombre'=>'Guazapa'],
			['id_departamento'=>'10','nombre'=>'Apopa'],
			['id_departamento'=>'10','nombre'=>'Nejapa'],
			['id_departamento'=>'10','nombre'=>'Cuscatancingo'],
			['id_departamento'=>'10','nombre'=>'Delgado'],
			['id_departamento'=>'10','nombre'=>'Ilopango'],
			['id_departamento'=>'10','nombre'=>'San Martín'],
			['id_departamento'=>'10','nombre'=>'Soyapango'],
			['id_departamento'=>'10','nombre'=>'Tonacatepeque'],
			['id_departamento'=>'10','nombre'=>'Ayutuxtepeque'],
			['id_departamento'=>'10','nombre'=>'Mejicanos'],
			['id_departamento'=>'10','nombre'=>'San Marcos'],
			['id_departamento'=>'10','nombre'=>'San Salvador'],
			['id_departamento'=>'10','nombre'=>'Santiago Texacuangos'],
			['id_departamento'=>'10','nombre'=>'Santo Tomás'],
			['id_departamento'=>'10','nombre'=>'Panchimalco'],
			['id_departamento'=>'10','nombre'=>'Rosario de Mora'],
			['id_departamento'=>'11','nombre'=>'Apastepeque'],
			['id_departamento'=>'11','nombre'=>'San Esteban Catarina'],
			['id_departamento'=>'11','nombre'=>'San Ildefonso'],
			['id_departamento'=>'11','nombre'=>'San Lorenzo'],
			['id_departamento'=>'11','nombre'=>'San Sebastián'],
			['id_departamento'=>'11','nombre'=>'Santa Clara'],
			['id_departamento'=>'11','nombre'=>'Santo Domingo'],
			['id_departamento'=>'11','nombre'=>'Guadalupe'],
			['id_departamento'=>'11','nombre'=>'San Cayetano Istepeque'],
			['id_departamento'=>'11','nombre'=>'San Vicente'],
			['id_departamento'=>'11','nombre'=>'Tecoluca'],
			['id_departamento'=>'11','nombre'=>'Tepetitán'],
			['id_departamento'=>'11','nombre'=>'Verapaz'],
			['id_departamento'=>'12','nombre'=>'Masahuat'],
			['id_departamento'=>'12','nombre'=>'Metapán'],
			['id_departamento'=>'12','nombre'=>'Santa Rosa Guachipilín'],
			['id_departamento'=>'12','nombre'=>'Texistepeque'],
			['id_departamento'=>'12','nombre'=>'Coatepeque'],
			['id_departamento'=>'12','nombre'=>'El Congo'],
			['id_departamento'=>'12','nombre'=>'Candelaria de la Frontera'],
			['id_departamento'=>'12','nombre'=>'Chalchuapa'],
			['id_departamento'=>'12','nombre'=>'El Porvenir'],
			['id_departamento'=>'12','nombre'=>'San Antonio Pajonal'],
			['id_departamento'=>'12','nombre'=>'San Sebastián Salitrillo'],
			['id_departamento'=>'12','nombre'=>'Santiago de la Frontera'],
			['id_departamento'=>'13','nombre'=>'Juayúa'],
			['id_departamento'=>'13','nombre'=>'Nahuizalco'],
			['id_departamento'=>'13','nombre'=>'Salcoatitán'],
			['id_departamento'=>'13','nombre'=>'Santa Catarina Masahuat'],
			['id_departamento'=>'13','nombre'=>'Nahulingo'],
			['id_departamento'=>'13','nombre'=>'San Antonio del Monte'],
			['id_departamento'=>'13','nombre'=>'Sonsonate'],
			['id_departamento'=>'13','nombre'=>'Santo Domingo'],
			['id_departamento'=>'13','nombre'=>'Sonzacate'],
			['id_departamento'=>'13','nombre'=>'Armenia'],
			['id_departamento'=>'13','nombre'=>'Caluco'],
			['id_departamento'=>'13','nombre'=>'Cuisnahuat'],
			['id_departamento'=>'13','nombre'=>'Izalco'],
			['id_departamento'=>'13','nombre'=>'San Julián'],
			['id_departamento'=>'13','nombre'=>'Santa Isabel Ishuatán'],
			['id_departamento'=>'13','nombre'=>'Acajutla'],
			['id_departamento'=>'14','nombre'=>'Alegría'],
			['id_departamento'=>'14','nombre'=>'Berlín'],
			['id_departamento'=>'14','nombre'=>'El Triunfo'],
			['id_departamento'=>'14','nombre'=>'Estanzuelas'],
			['id_departamento'=>'14','nombre'=>'Jucuapa'],
			['id_departamento'=>'14','nombre'=>'Mercedes Umaña'],
			['id_departamento'=>'14','nombre'=>'Nueva Granada'],
			['id_departamento'=>'14','nombre'=>'San Buenaventura'],
			['id_departamento'=>'14','nombre'=>'Santiago de María'],
			['id_departamento'=>'14','nombre'=>'California'],
			['id_departamento'=>'14','nombre'=>'Concepción Batres'],
			['id_departamento'=>'14','nombre'=>'Ereguayquín'],
			['id_departamento'=>'14','nombre'=>'Jucuarán'],
			['id_departamento'=>'14','nombre'=>'Ozatlán'],
			['id_departamento'=>'14','nombre'=>'San Dionisio'],
			['id_departamento'=>'14','nombre'=>'Santa Elena'],
			['id_departamento'=>'14','nombre'=>'Santa María'],
			['id_departamento'=>'14','nombre'=>'Tecapán'],
			['id_departamento'=>'14','nombre'=>'Usulután'],
			['id_departamento'=>'14','nombre'=>'Jiquilisco'],
			['id_departamento'=>'14','nombre'=>'Puerto El Triunfo'],
			['id_departamento'=>'14','nombre'=>'San Francisco Javier'],
			['id_departamento'=>'14','nombre'=>'San Agustín']
		];
		foreach ($municipios as $municipio) {
            Municipio::create($municipio);
        }
	}
}